services:
  fauxqs:
    image: kibertoad/fauxqs:2.3.1
    ports:
      - '127.0.0.1:4566:4566'
    environment:
      - FAUXQS_INIT=/app/init.json
      - FAUXQS_LOGGER=true
    volumes:
      - ./init.json:/app/init.json:ro
