/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PasswordUpdateRouteImport } from './routes/password-update'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CatalogRouteImport } from './routes/_catalog'
import { Route as CatalogIndexRouteImport } from './routes/_catalog/index'
import { Route as CatalogCartRouteImport } from './routes/_catalog/cart'
import { Route as CatalogProductsProductIdRouteImport } from './routes/_catalog/products.$productId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PasswordUpdateRoute = PasswordUpdateRouteImport.update({
  id: '/password-update',
  path: '/password-update',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/_catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogCartRoute = CatalogCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => CatalogRoute,
} as any)
const CatalogProductsProductIdRoute =
  CatalogProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => CatalogRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof CatalogIndexRoute
  '/login': typeof LoginRoute
  '/password-update': typeof PasswordUpdateRoute
  '/signup': typeof SignupRoute
  '/cart': typeof CatalogCartRoute
  '/products/$productId': typeof CatalogProductsProductIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/password-update': typeof PasswordUpdateRoute
  '/signup': typeof SignupRoute
  '/cart': typeof CatalogCartRoute
  '/': typeof CatalogIndexRoute
  '/products/$productId': typeof CatalogProductsProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_catalog': typeof CatalogRouteWithChildren
  '/login': typeof LoginRoute
  '/password-update': typeof PasswordUpdateRoute
  '/signup': typeof SignupRoute
  '/_catalog/cart': typeof CatalogCartRoute
  '/_catalog/': typeof CatalogIndexRoute
  '/_catalog/products/$productId': typeof CatalogProductsProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/password-update'
    | '/signup'
    | '/cart'
    | '/products/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/password-update'
    | '/signup'
    | '/cart'
    | '/'
    | '/products/$productId'
  id:
    | '__root__'
    | '/_catalog'
    | '/login'
    | '/password-update'
    | '/signup'
    | '/_catalog/cart'
    | '/_catalog/'
    | '/_catalog/products/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CatalogRoute: typeof CatalogRouteWithChildren
  LoginRoute: typeof LoginRoute
  PasswordUpdateRoute: typeof PasswordUpdateRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/password-update': {
      id: '/password-update'
      path: '/password-update'
      fullPath: '/password-update'
      preLoaderRoute: typeof PasswordUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_catalog': {
      id: '/_catalog'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_catalog/': {
      id: '/_catalog/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/_catalog/cart': {
      id: '/_catalog/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CatalogCartRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/_catalog/products/$productId': {
      id: '/_catalog/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof CatalogProductsProductIdRouteImport
      parentRoute: typeof CatalogRoute
    }
  }
}

interface CatalogRouteChildren {
  CatalogCartRoute: typeof CatalogCartRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogProductsProductIdRoute: typeof CatalogProductsProductIdRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogCartRoute: CatalogCartRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogProductsProductIdRoute: CatalogProductsProductIdRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CatalogRoute: CatalogRouteWithChildren,
  LoginRoute: LoginRoute,
  PasswordUpdateRoute: PasswordUpdateRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
